version: "3"
services:
  php:
    build:
      args:
        user: sysuser
        uid: 1001
      context: .
      dockerfile: Dockerfile
    image: application
    container_name: laravelphp
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravelnetwork
    depends_on:
      - mysql
    tty: true

  mysql:
    image: mysql:latest
    container_name: laravelmysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_USERNAME: "laraveluser"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "laraveldb"
    volumes:
      - ./db:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravelnetwork

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: laravelpma
    ports:
      - 80:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 128M
    depends_on:
      - mysql
    networks:
      - laravelnetwork

  nginx:
    image: nginx:latest
    container_name: laravelnginx
    restart: unless-stopped
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./src:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - laravelnetwork
    depends_on:
      - mysql
      - php

  node:
    image: node:22-alpine
    container_name: laravelnode
    working_dir: /var/www
    ports:
      - "5173:5173"
    volumes:
      - ./src:/var/www
    networks:
      - laravelnetwork
    tty: true
    stdin_open: true

networks:
  laravelnetwork:
    driver: bridge

volumes:
  db:
    driver: local
